### ISSUE TITLE
gvmtool fails to install during Vagrant provisioning

### ISSUE THREAD

**Issue by jkins** [ozone-development/dev-tools#13]
The provisioning script attempts to install gvmtool from a URL, which now redirects to sdkman, a newer and rebranded gvmtool. This causes gvmtool installation to silently fail, and later causes marketplace.war build failure (since grails never gets installed).

Relevant log entries:
```
==> ozp-centos6.6: /vagrant/initial_provisioning.sh: line 22: /home/vagrant/.gvm/bin/gvm-init.sh: No such file or directory
==> ozp-centos6.6: /vagrant/initial_provisioning.sh: line 30: /home/vagrant/.gvm/etc/config: No such file or directory
==> ozp-centos6.6: /vagrant/initial_provisioning.sh: line 33: gvm: command not found
==> ozp-centos6.6: /vagrant/initial_provisioning.sh: line 34: gvm: command not found
==> ozp-centos6.6: /vagrant/initial_provisioning.sh: line 35: gvm: command not found
...
==> ozp-centos6.6: /vagrant/build.sh: line 17: /home/vagrant/.gvm/bin/gvm-init.sh: No such file or directory
==> ozp-centos6.6: /vagrant/build.sh: line 18: gvm: command not found
==> ozp-centos6.6: /vagrant/build.sh: line 19: gvm: command not found
...
==> ozp-centos6.6: cp: 
==> ozp-centos6.6: cannot stat `ozp-rest/target/marketplace.war'
==> ozp-centos6.6: : No such file or directory
...
==> ozp-centos6.6: mv: 
==> ozp-centos6.6: cannot stat `marketplace.war'
==> ozp-centos6.6: : No such file or directory
==> ozp-centos6.6: chown: 
==> ozp-centos6.6: cannot access `/var/lib/tomcat/webapps/marketplace.war'
==> ozp-centos6.6: : No such file or directory
...
==> ozp-centos6.6: {"error":"IndexMissingException[[marketplace] missing]","status":404}
```

I believe this is the root cause for issue #12.

**Comment by tonyalletag** [comment]
**Vagrant Issues/Updates**
the gvm tool no longer exist and has been replaced with sdkman.  This was causing Groovy and Grails to fail when installing. The end result of the vagrant script was an OZP front end with no backend. Updates to the vagrant script have been posted to GitHub.  

**Updates to initial_provisioning.sh**
`curl -s get.sdkman.io | bash`
`source "$HOME/.sdkman/bin/sdkman-init.sh"`
`sdk install groovy`
`sdk install grails 2.3.7`

**updates to build.sh**
`source $HOME/.sdkman/bin/sdkman-init.sh`
`sdk use grails 2.3.7`
`sdk current grails`

**Steps to use updated vagrant script:**
pull the latest updates on the dev-tools git repo
`vagrant halt`
`vagrant destroy`
`vagrant up`

**Steps get vagrant box working use via vagrant ssh**
`vagrant ssh`
`curl -s get.sdkman.io | bash`
`source "$HOME/.sdkman/bin/sdkman-init.sh"`
`sdk install groovy`
`sdk install grails 2.3.7`

`grails war`
`sudo mv marketplace.war /usr/share/tomcat/webapps`
`sudo tomcat service stop`
`sudo tomcat service start`
