### ISSUE TITLE
Vagrant Plugin install not working

### ISSUE THREAD

**Issue by antman1p** [ozone-development/dev-tools#4]
I have 2 issues:

1)  I am following the instructions and am running the following command in the Windows 7 cmd:  
vagrant plugin install vagrant-vbguest

I keep getting the error:

C:\HashiCorp\Vagrant>vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most like
ly your system doesn't have the CA certificates needed for verification. For inf
ormation about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without usi
ng SSL, edit your Gemfile sources and change 'https' to 'http'.

Retrying source fetch due to error (2/3): Bundler::Fetcher::CertificateFailureEr
ror Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most like
ly your system doesn't have the CA certificates needed for verification. For inf
ormation about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without usi
ng SSL, edit your Gemfile sources and change 'https' to 'http'.Retrying source f
etch due to error (3/3): Bundler::Fetcher::CertificateFailureError Could not ver
ify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most like
ly your system doesn't have the CA certificates needed for verification. For inf
ormation about OpenSSL certificates, see bit.ly/ruby-ssl. To connect without usi
ng SSL, edit your Gemfile sources and change 'https' to 'http'.

I am not seeing ay additional steps or prereq's in the instructions complete this step.  Please let me know what I am missing.

2)  I the following part of the instructions, I am not sure which path the instructions are referring to when it says "YOUR PATH.  Please advise.

"3. Next, you have to customize some files. - Open Vagrantfile, change line 52 and change it to match YOUR PATH The original line is: config.vm.synced_folder "~/ozp/", "/home/vagrant/ozp", type: "rsync", rsync__exclude: "**/*.git/""

Thank you.

**Comment by arw180** [comment]
For your first issue, try adding `--plugin-source http://rubygems.org` to the command - i.e.: `vagrant plugin install vagrant-vbguest --plugin-source http://rubygems.org`. 

I'm not sure exactly which instructions your second and third questions are referring to, but from the looks of it, YOUR PATH equates to the directory on your host machine that contains the files you want to be rsynced over to the vagrant box. The default is the `ozp` directory in your home directory - i.e. `~/ozp/`. Note that you can also just remove that line entirely from the vagrant file - it's just a development preference.

**Comment by antman1p** [comment]
OK, thank you.  I tried your suggestion and got this:


C:\HashiCorp\Vagrant>vagrant plugin install vagrant-vbguest --plugin-source
http
://rubygems.org
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:
An error occurred while installing rdoc (4.2.0), and Bundler cannot
continue.
Make sure that `gem install rdoc -v '4.2.0'` succeeds before bundling.
Gem::RemoteFetcher::FetchError: bad response UnspecificError 403 (
http://rubygem
s.global.ssl.fastly.net/gems/rdoc-4.2.0.gem)

**Comment by tonyalletag** [comment]
The OZP Dev team will be releasing an updated OZP-In-a-Box vagrant script for the python backend in the next week or two.  This will be for CentOS only. The OZP Dev team only has the resources to test, update, and support CentOS or yum based OS vagrant box.  Those wanting support for Windows or other OS are free to make contributions to the code base.
After this update the OZP Dev team will no longer be updating the java backend vagrant boxes and will only continue to update the python backend vagrant boxes.

**Comment by kenorb** [comment]
Related: mitchellh/vagrant/issues/7787
