### ISSUE TITLE
iwc legacy adapter not installed correctly

### ISSUE THREAD

**Issue by arw180** [ozone-development/dev-tools#7]
We've had reports that the IWC legacy adapter is not being installed correctly

**Comment by ruckc** [comment]
It appears that this is failing for me in the `npm run build` step from `build.sh`.

The error I get is:

```
sh: grunt: command not found
npm ERR! weird error 127
npm ERR! not ok code 0
```

**Comment by arw180** [comment]
I'm not sure why that's happening - are you on a Windows host by chance?

To get around that, you can do a `sudo npm install -g grunt` manually before running `build.sh` again.

**Comment by tonyalletag** [comment]
The OZP Dev team will be releasing an updated OZP-In-a-Box vagrant script for the python backend in the next week or two.  This will be for CentOS only. The OZP Dev team only has the resources to test, update, and support CentOS or yum based OS vagrant box.  Those wanting support for Windows or other OS are free to make contributions to the code base.
After this update the OZP Dev team will no longer be updating the java backend vagrant boxes and will only continue to update the python backend vagrant boxes.
