### ISSUE TITLE
Webtop Not Working Properly

### ISSUE THREAD

**Issue by itaran** [ozone-development/dev-tools#8]
When running the Vagrant version of OZP..

When we brought up web top none of the buttons were working, and the dashboard selector didn't have the dashboard name rather it had {{.....}}

The issue turned out to be /ozp-static-deployment/webtop/OzoneConfig.js file.

there was a missing variable
"HELPDESK_ADDRESS": ....

We added that in based on the OzoneConfig.js file associated with center at /ozp-static-deployment/center and it started working.

**Comment by clarkjefcoat** [comment]
@itaran - Does your deploy.sh match the latest version in the dev-tools repo?  We checked-in an updated version last week that should address the HELPDESK_ADDRESS issue that you mentioned.

**Comment by Kevin-K** [comment]
The redeploy script for webtop did not include the HELPDESK_ADDRESS overwriting for the OzoneConfig.js file. I just updated it hopefully it fixes future issues.
